name: PEP8 Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint with Black, Isort, and Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - - name: Run black
          run: black --check --diff --line-length 88 $(git ls-files '*.py')


      - name: Run Isort
        run: isort --check-only --diff .

      - name: Run Flake8
        run: flake8 .
